### ISSUE TITLE
UTF8 BOM error

### ISSUE THREAD

**Issue by kolomenkin** [meequz/exchange-tools#1]
Traceback (most recent call last):
  File "nbrb-kurs.py", line 112, in <module>
    xml_file.write(xml)
  File "c:\dev\python-3.6.0-64\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>

I was using freshly installed python 3.6.0 64 bit in Windows 10.
I was running your tool without arguments.

BTW, "\ufeff" is a usual BOM marker. It may happen NBRB.BY returned XML with UTF8 BOM at the beginning.

**Comment by meequz** [comment]
Wow, someone interested in this! I wonder how did you find the repo?
I'll check the PR.

**Comment by kolomenkin** [comment]
I've tried googling something like "python nbrb.by" to find python samples for NBRB API
